# Generated by Django 5.0.6 on 2024-07-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('url_website', models.URLField(verbose_name='Website URL')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
