# Generated by Django 5.0.6 on 2024-07-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url_website',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
    ]
